1)Створіть одновимірний масив (вектор) з сумами добутків двох попередніх чисел та
їхнього суми, починаючи з 1, та виведіть його значення

In [1]:
import numpy as np

# Початкові значення
a = 1
b = 1

# Визначаємо розмір масиву
n = 10  # наприклад, 10 елементів

# Ініціалізація масиву з нулями
result_array = np.zeros(n)

# Заповнення масиву значеннями
for i in range(n):
    product = a * b  # добуток попередніх двох чисел
    summation = a + b  # сума попередніх двох чисел
    result_array[i] = product + summation  # записуємо результат у масив

    # Оновлення a і b для наступної ітерації
    a, b = b, product + summation

# Виведення масиву
print("Результуючий масив:", result_array)


Результуючий масив: [3.00000000e+00 7.00000000e+00 3.10000000e+01 2.55000000e+02
 8.19100000e+03 2.09715100e+06 1.71798692e+10 3.60287970e+16
 6.18970020e+26 2.23007452e+43]


2)Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
випадкових цілих чисел від -10 до 10.

In [1]:
import numpy as np

# Визначення розміру матриці
rows, cols = 3, 3

# Створення матриці з випадкових цілих чисел від -10 до 10
matrix = np.random.randint(-10, 11, size=(rows, cols))

# Виведення матриці
print("Матриця 3x3 з випадковими цілими числами від -10 до 10:")
print(matrix)


Матриця 3x3 з випадковими цілими числами від -10 до 10:
[[-10   2   4]
 [ -3   8  10]
 [ -1  -9  -4]]


3)Створіть масив розміром 5x5, заповніть його випадковими дійсними числами від 0 до
1 та знайдіть відсоток чисел, які є простими.

In [3]:
import numpy as np
from sympy import isprime

# Створення матриці 5x5 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(5, 5)

# Округлення чисел до найближчих цілих
rounded_matrix = np.rint(matrix).astype(int)

# Функція для підрахунку простих чисел
def count_primes(matrix):
    prime_count = 0
    total_count = matrix.size
    for num in matrix.flatten():
        if isprime(num) and num > 1:
            prime_count += 1
    return (prime_count / total_count) * 100

# Знаходимо відсоток простих чисел після округлення
percentage_of_primes = count_primes(rounded_matrix)

# Виведення матриці та відсотка простих чисел
print("Матриця 5x5 з випадковими дійсними числами від 0 до 1:")
print(matrix)
print("\nМатриця після округлення до найближчих цілих чисел:")
print(rounded_matrix)
print(f"\nВідсоток простих чисел у матриці: {percentage_of_primes:.2f}%")


Матриця 5x5 з випадковими дійсними числами від 0 до 1:
[[0.587137   0.20511401 0.95259728 0.26061774 0.1634582 ]
 [0.77095606 0.01636869 0.61880037 0.34750469 0.90300228]
 [0.78540774 0.76310731 0.19095723 0.03225447 0.05020952]
 [0.17596233 0.04981281 0.66228985 0.9594635  0.95698083]
 [0.2543853  0.59566248 0.41698615 0.05051294 0.64798179]]

Матриця після округлення до найближчих цілих чисел:
[[1 0 1 0 0]
 [1 0 1 0 1]
 [1 1 0 0 0]
 [0 0 1 1 1]
 [0 1 0 0 1]]

Відсоток простих чисел у матриці: 0.00%


4)Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від -1.1 до 1.1 та виведіть його значення.


In [4]:
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами в діапазоні від -1.1 до 1.1
matrix = np.random.uniform(-1.1, 1.1, size=(3, 3))

# Виведення матриці
print("Матриця 3x3 з випадковими дійсними числами від -1.1 до 1.1:")
print(matrix)


Матриця 3x3 з випадковими дійсними числами від -1.1 до 1.1:
[[-0.50302627  0.26147256  1.03464218]
 [-0.92516776 -0.17357111 -0.16353404]
 [-0.44626242 -0.99389737 -1.07569033]]


5)Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими
числами в діапазоні від 15 до 25 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [5]:
import numpy as np

# Створення двох одновимірних масивів розміром 4 з випадковими цілими числами в діапазоні від 15 до 25
array1 = np.random.randint(15, 26, size=4)
array2 = np.random.randint(15, 26, size=4)

# Виконання поелементних операцій
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виведення результатів
print("Масив 1:")
print(array1)

print("\nМасив 2:")
print(array2)

print("\nПоелементне додавання:")
print(addition)

print("\nПоелементне віднімання:")
print(subtraction)

print("\nПоелементне множення:")
print(multiplication)


Масив 1:
[18 20 24 23]

Масив 2:
[23 22 22 19]

Поелементне додавання:
[41 42 46 42]

Поелементне віднімання:
[-5 -2  2  4]

Поелементне множення:
[414 440 528 437]


6)Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 10 та
знайдіть їх добуток.

In [6]:
import numpy as np

# Створення двох матриць 3x3 з випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

# Обчислення добутку матриць
product_matrix = np.dot(matrix1, matrix2)

# Виведення результатів
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nДобуток матриць:")
print(product_matrix)


Матриця 1:
[[ 6  5  4]
 [ 4  2  7]
 [ 1  7 10]]

Матриця 2:
[[ 4  7  1]
 [ 3 10  4]
 [10  6  2]]

Добуток матриць:
[[ 79 116  34]
 [ 92  90  26]
 [125 137  49]]


7)Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [7]:
import numpy as np

# Створення матриці 2x3 з випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, size=(2, 3))

# Створення матриці 3x3 з випадковими цілими числами від 1 до 5
matrix2 = np.random.randint(1, 6, size=(3, 3))

# Обчислення добутку матриць
product_matrix = np.dot(matrix1, matrix2)

# Виведення результатів
print("Матриця 2x3:")
print(matrix1)

print("\nМатриця 3x3:")
print(matrix2)

print("\nДобуток матриць:")
print(product_matrix)


Матриця 2x3:
[[2 5 5]
 [3 5 1]]

Матриця 3x3:
[[2 1 3]
 [1 3 4]
 [3 5 5]]

Добуток матриць:
[[24 42 51]
 [14 23 34]]


8)Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 7 та знайдіть її обернену матрицю.

In [8]:
import numpy as np

# Створення матриці 2x2 з випадковими цілими числами від 1 до 7
matrix = np.random.randint(1, 8, size=(2, 2))

# Функція для обчислення оберненої матриці
def invert_matrix(matrix):
    try:
        # Обчислення оберненої матриці
        inv_matrix = np.linalg.inv(matrix)
        return inv_matrix
    except np.linalg.LinAlgError:
        # Якщо матриця сингулярна (не має оберненої матриці)
        return "Матриця не має оберненої матриці"

# Обчислення оберненої матриці
inverse_matrix = invert_matrix(matrix)

# Виведення результатів
print("Матриця 2x2:")
print(matrix)

print("\nОбернена матриця:")
print(inverse_matrix)


Матриця 2x2:
[[3 1]
 [3 4]]

Обернена матриця:
[[ 0.44444444 -0.11111111]
 [-0.33333333  0.33333333]]


9)Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 5 до 10 та транспонуйте її.

In [9]:
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами в діапазоні від 5 до 10
matrix = np.random.uniform(5, 10, size=(3, 3))

# Транспонування матриці
transposed_matrix = np.transpose(matrix)

# Виведення результатів
print("Матриця 3x3:")
print(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)


Матриця 3x3:
[[5.69201622 9.41650643 9.52629693]
 [8.83269935 8.98427775 9.87724694]
 [6.3130572  7.96261873 6.4671099 ]]

Транспонована матриця:
[[5.69201622 8.83269935 6.3130572 ]
 [9.41650643 8.98427775 7.96261873]
 [9.52629693 9.87724694 6.4671099 ]]


10)Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.

In [10]:
import numpy as np

# Створення матриці 3x4 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(3, 4))

# Створення вектора 4x1 з випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, size=(4, 1))

# Обчислення добутку матриці на вектор
product = np.dot(matrix, vector)

# Виведення результатів
print("Матриця 3x4:")
print(matrix)

print("\nВектор 4x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(product)


Матриця 3x4:
[[0.17324886 0.92851167 0.11766022 0.26537472]
 [0.96884046 0.95225153 0.67174223 0.4079219 ]
 [0.34375067 0.25436413 0.17095461 0.38484761]]

Вектор 4x1:
[[0.45325899]
 [0.71610808]
 [0.47277262]
 [0.63325925]]

Добуток матриці на вектор:
[[0.96711884]
 [1.69695231]
 [0.66249127]]


11)Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [11]:
import numpy as np

# Створення матриці 2x3 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(2, 3))

# Створення вектора 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

# Обчислення добутку матриці на вектор
product = np.dot(matrix, vector)

# Виведення результатів
print("Матриця 2x3:")
print(matrix)

print("\nВектор 3x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(product)


Матриця 2x3:
[[ 8 10  2]
 [ 5  5  2]]

Вектор 3x1:
[[6]
 [1]
 [6]]

Добуток матриці на вектор:
[[70]
 [47]]


12)Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від -2 до 2 та знайдіть суму всіх елементів обох матриць.

In [12]:
import numpy as np

# Створення двох матриць 2x2 з випадковими цілими числами від -2 до 2
matrix1 = np.random.randint(-2, 3, size=(2, 2))
matrix2 = np.random.randint(-2, 3, size=(2, 2))

# Обчислення суми всіх елементів обох матриць
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)
total_sum = sum_matrix1 + sum_matrix2

# Виведення результатів
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nСума всіх елементів Матриці 1:")
print(sum_matrix1)

print("\nСума всіх елементів Матриці 2:")
print(sum_matrix2)

print("\nСума всіх елементів обох матриць:")
print(total_sum)


Матриця 1:
[[ 2  2]
 [-2  1]]

Матриця 2:
[[ 1 -2]
 [-1  2]]

Сума всіх елементів Матриці 1:
3

Сума всіх елементів Матриці 2:
0

Сума всіх елементів обох матриць:
3


13) Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть суму їх елементів.


In [13]:
import numpy as np

# Створення двох матриць 3x3 з випадковими дійсними числами від 0 до 1
matrix1 = np.random.uniform(0, 1, size=(3, 3))
matrix2 = np.random.uniform(0, 1, size=(3, 3))

# Обчислення суми всіх елементів кожної матриці
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)
total_sum = sum_matrix1 + sum_matrix2

# Виведення результатів
print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nСума всіх елементів Матриці 1:")
print(sum_matrix1)

print("\nСума всіх елементів Матриці 2:")
print(sum_matrix2)

print("\nСума всіх елементів обох матриць:")
print(total_sum)


Матриця 1:
[[0.32886281 0.103516   0.59796882]
 [0.61183552 0.88220979 0.00971164]
 [0.90723114 0.85300881 0.12680221]]

Матриця 2:
[[0.16812021 0.77418293 0.20670926]
 [0.07906064 0.09197425 0.48155685]
 [0.27031764 0.10457366 0.22703027]]

Сума всіх елементів Матриці 1:
4.421146726312617

Сума всіх елементів Матриці 2:
2.403525711004394

Сума всіх елементів обох матриць:
6.824672437317012


14)Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -10 до 10 та знайдіть суму елементів на побічній діагоналі.

In [14]:
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами від -10 до 10
matrix = np.random.uniform(-10, 10, size=(3, 3))

# Обчислення суми елементів на побічній діагоналі
# Побічна діагональ має індекси (0,2), (1,1), (2,0)
sum_secondary_diagonal = np.sum([matrix[i, 2-i] for i in range(3)])

# Виведення результатів
print("Матриця 3x3:")
print(matrix)

print("\nСума елементів на побічній діагоналі:")
print(sum_secondary_diagonal)


Матриця 3x3:
[[ 4.64971248 -9.44701731 -7.49553868]
 [-3.73411366 -6.71213978  2.21352389]
 [ 6.44039542  6.82822221 -0.06842785]]

Сума елементів на побічній діагоналі:
-7.767283041865948


15)Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найбільший елемент у
кожному стовпці матриці.

In [15]:
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(3, 3))

# Знаходження найбільшого елемента в кожному стовпці
max_elements = np.max(matrix, axis=0)

# Перетворення масиву в вектор-стовпчик
vector_column = max_elements.reshape(-1, 1)

# Виведення результатів
print("Матриця 3x3:")
print(matrix)

print("\nВектор-стовпчик, що містить найбільший елемент у кожному стовпці:")
print(vector_column)


Матриця 3x3:
[[0.27619036 0.54530917 0.62695468]
 [0.6498351  0.04090073 0.90028221]
 [0.26820646 0.77682988 0.74198144]]

Вектор-стовпчик, що містить найбільший елемент у кожному стовпці:
[[0.6498351 ]
 [0.77682988]
 [0.90028221]]


Висновок: Засвоїли використання ColabGoogle. Ми навчилися створювати матриці різних розмірів та заповнювати їх випадковими значеннями у заданих діапазонах.Знаходження суми всіх елементів матриць. Визначення суми елементів на основній та побічній діагоналях матриці. Матричні операції: Виконання матричних операцій, таких як добуток матриці на вектор.Транспонування матриці: Зміна розташування рядків і стовпців матриці для отримання транспонованої версії. Ці знання дозволяють ефективно працювати з даними у вигляді матриць і векторів, що є основою для багатьох чисельних і наукових обчислень.